### ISSUE TITLE
Get the latest, not a fixed 0.35.0 version.

### ISSUE THREAD

**Issue by techcobweb** [adamcoulthard/homebrew-tap#1]
As a galasa user, I want the formula to remain up to date even when newer versions of galasactl are available.

The current implementation is limited to drawing on v0.35.0 only, and will need updating whenever a new version of the galasactl tool is made available. 

Or perhaps this is this not how brew works ? Having hard-coded sha sums inside the script would at least verify that the correct binary content was being downloaded.
If that's the case, how would we maintain the brew formular whenever a new version of galasactl was released ? Some instructions in the readme on how to do that might go a long way... and we could add it to our list in our 'release process' steps.

From a little reading, perhaps we should be calling this formula `galasactl@0.35.0` or similar, then it leaves the door open for `galasactl@0.36.0` ...etc ?
And we can bump the formula by re-delivering a newer version to tap ?

Also the readme instructions of `tap adamcouthard/galasactl` don't work, you missed the `brew` command off the front.

You are also going to have to add a `license "EPL-2.0"` line or something before you can deliver this formula. See https://docs.brew.sh/Formula-Cookbook#fill-in-the-license 
> We don’t accept new formulae into Homebrew/homebrew-core without a [license](https://rubydoc.brew.sh/Formula#license-class_method)!

**Comment by adamcoulthard** [comment]
Pushed a new commit with versions going back to 0.33.0 we could go back further but I'm not sure it's worth it.  I've also updated the README as well with what is required.  I suspect a simple script would be easy to create to do the release processing.
